version: '3.6'

services: 
  server:
    image: bowlpool_server:master
    env_file:
      - .env
    expose:
      - '1313'
    ports:
      - '1313:1313'
    command: yarn start
  
  web:
    depends_on:
      - server
    image: bowlpool_web:master
    env_file:
      - ./Web/.env
    expose:
      - "80"
    ports:
      - "80:80"
