version: '3.6'

services:
  server:
    image: bowlpool_server
    env_file:
      - ./Server/.env
    expose:
      - '1313'
    ports:
      - '1313:1313'
    command: yarn start
    networks:
      - bowlpool

  web:
    depends_on:
      - server
    image: bowlpool_web
    env_file:
      - ./Web/.env
    expose:
      - '80'
    ports:
      - '80:80'
    networks:
      - bowlpool

networks:
  bowlpool:
    name: bowlpool
    external: true
