version: '3.6'

services: 
  server:
    build: 
      context: ./Server
      target: base
    env_file:
      - .env
    expose:
      - '1313'
    ports:
      - '1313:1313'
    command: yarn start
  
  web:
    depends_on:
      - server
    build: 
      context: ./Web
      target: baseweb
    env_file:
      - ./Web/.env
    expose:
      - "80"
    ports:
      - "80:3000"
    command: yarn start