name: Deploy Testing

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Testing Server
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    
    - name: docker-compose
      run: |
       docker-compose up -d -no-deps --build
       docker system prune -f
